language: python
python:
- '2.7'

sudo: required

install:
- pip install .

# Run the doctest
script:
- python setup.py test

deploy:

  - provider: releases
    skip_cleanup: true
    api-key:
        secure: ctpbaLbv/oEXCpnZDjuzN5z9+/vzV8+wj94ipzXpGAhhri38iF+PQKtiUXrWBq0bw7u7UZynyK2EUhdPgIx/nBlAY/b+spH5dKwbPVHyEfEHii1sopQBXd0ZQoeI9f8MqY/OmBu4x2XMJ6+0h1vs4pJ6BoLY9Hc/QZolATCNASkJHXbKEa4Ut8m0BdHYLdzyBze6+LGTqe7K5eWwYk8LK2TpORFEixCatzmsRyZALmlkeIDKGnmU77FNkjubeZ3zqUNwwK5SZaBOdo4l+wfRdlqqv7M5NNzHxHlDaKSAblI021Ypl3jxLgH6vs6G0AWqQwJnYDdcVqJiEqK/6cfoMw/iEClbGylF8kNU0urWA0T8QgipIhJoUnl7YOJcCRxuJpgZTztI9xQMfLVp7r7l9IHS+dUdnf7GRs/UfNv1zfmKbuc0NLtKeGk7aYDcrMBNVOQGqwdDCxH2NB+PHC58XLxeOFH1klHDElYPRKsAY2YgvZg9Rls/cEtookcI1VljRHso+4x7h6xMVkv/zJTClkX9nTA7WGYbIqysu5paUVbMkuSA4BDysSGKg8V/NM7/0K+jAfXeiNcDvHy7re5ZMQSNHZf3DgsoNNxtazOa6Fvo+tWXoKwzvWGx1PNBHh3++6EKGQbgkplPYj8gNzC673hMpagaZZpBJPfTR8SXdNA=
    name: logagg-utils-0.5.0
    tag_name: 0.5.0
    on:
        branch: master
        repo: deep-compute/logagg-utils

  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    user: "deepcompute"
    password:
        secure: "W1S8ZTPZ4T3onLYRIoXdOGLPL1fLTIang4DU28eGSHiPeDtv4Vj7HCs5ykPuTLuczU77Ry+phnxYznV0hcA+mYTlgyrVEbi62K+BZjLKLt86+KzJzhiivSRQL7YbYXGBoQte2DCNk3g6bytdHfWvx3wL/mj0gJ8wePJ83xeoiC4+TgsDvChFvNnMz2nv6yuQkcV9j1kX8A9Jto91ZFvksXc4qGI/VtB+Cah7K1M8lPYaVmyf1Gft1bRRbl4+RR+SQXTpa6GbzZzWMCiRC6Pcs2LrzYVoIblAKBXzOQ35+QL8Uj82pkXPZaBfMwXZET8vtpLvwyk0Nn34vAeX6pt5YSHsM5/CvUlQXHCiDFKJ+p57HSxHF70hak0qnFfh7g7hS7X37d5wnVTZruG9GCJStNYE2XB1JA3xgZsownjHrjVrG7azvS/Ia2kXi0/XG45OJj2cU6AgoioUIksMxAzzK3qmkUXUmXztSRp79Hz2Vi6FjBBw7Um3OZHluXAGvRugfFQju49HDT5KCr+RkFD59sZzOEBnFwbXHI/2QbtoA5D4bOWzjDg7L0XcGhACvwSVXKuMe8in5e6Z+09zUYJb/qJS9AhkXvahYIFx+4jvRH5nK0YCmNgdof3KrytAoE8BiyKLwmkZ93J/o70ZxETnnd2Jo/s7HebncKMNZJlpWmA="
    on:
      branch: master
      # only when there is a release it will update pypi
      tags: true
