language: python
python:
- '3.6.5'

sudo: required

install:
- pip install .

# Run the doctest
script:
- python setup.py test

deploy:
  provider: releases
  skip_cleanup: true 
  api_key:
    secure: qWehvGexP/5KkYNaPNl+HrI4jMEvB+3Odn0zNZYkZYNBtoc/wx+9fNwNcuhzfetgSh4yjKMDs7J9snoANC+j9rlpAgRWQYgA4znxHv7w7wcDvN+ZPxFvcNUpWanfs+0EO3iUJeZO3arqJseYhP3Od4YnakOpInVeCB2oKxJQ4T3QS6yVHWUzsbrBMSdW6R36VHFVmiTPf0VHHCWo0UJt9xXjXlqPwbdO778GJ2UvUypjpXLubQAJaBXZy6Kj0ixDOURGsWOU3dXf9Vx52YYA1ITvj9DFML2IWk6Mroc9suR3C6E7a7Cf2cyZYXXR88hQ+USc+F76pNtW4nYxj7IXYIckxTs4GvXIb4/yKFYhsVDRbDGlbfHpHTpLFy/N+L26Q7Ypo1IHV+t8XuSVo29sZrC4L/KI4f+dVAGbwsLPGYyDoU6BJ0IPc1h77dDhUZFjQnafQu7HrXqLehfb2b8VH76s9vRJzMEqd/1Lc4ET50pfL90VdAQWyaqeabd+Z99QAwNOCjg/0CQLY6MnDzLtcn4ceIspsmCJQqGpEtS9P/U/ZgnjSouULaRkwrJxksjgN00Tc7bdnRTI+L8dHPt0ekhl3EgCjeSylkkPZat3NWOcYhX/ilExHPRb6qOcrnvi0Au4lXZHjaZRX3tAuhY55H78CVGstTEbNEg45G9ebdM=
  name: logagg-utils-0.5.0
  tag_name: 0.5.0
  on:
    repo: deep-compute/logagg-utils
