before_install:
- pip3 install black
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: YUf26ENaTNB6HwGZJn/DdfrXjWsUpY/9ZAazFw8bSr1PMqSJ36dhYXLBxIAVODp1naRSzogQDXYe320wcQuVFaSoYlTIa/vSybGtEAbKclrarKruCzFfRO7xHm2XVW0W20f9TM4gYuSq31CNj5et/gCoF4ssF4h8vgDjx7lRxO9nTwa1L1AFimuiDiYtGlbvcpifBwkhkef5U2uLLF9x48IOaW3Attv1INr5HCbEiGhQCr/4WeWHg/WTFtFdX5XdrsoI8fz3PZHtJ3opzXTNk5EmI1ZqqtrDN4x4HcgwTE4PxC2cPM/Sf/UG/h8guPZl4qL+2RICURku1SLC89fLfmDZMrtdvOZoEHx6QzGBzw347xC3hVPGNrY8O1aNfGH/PfWe3Fn5PBhDpb/aCo30sABX6kmrt0a0dzc/jpivdENLA/1CCSSWin6p39cqvrV+VX4uZJl+HljdHV1w6JMlegfFZbWmYBquO7ApLmuTwclmxzbnnCywzzN3OO+yG0xqQjQu5wA3+x724rhxxFT3oHDBTZ9L65unhvKYAlPTOwrT2akgpYRQH4ce29h6P+Yn5EWtkD/PQpqLg0j8gLlC7f4dJChNmY7YFSA7f+WIjfeLsyl3+hWy6iIVuKaR6kUsL6XyIm1HPhkuchet01WyTllFY40/u0rUncs5/OrDhvU=
  name: logagg-utils-0.5.2
  tag_name: 0.5.2
  true:
    branch: master
    repo: deep-compute/logagg-utils
- provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: deepcompute
  password:
    secure: MU9rLDRiDgA438Izti8qJ5Y/DnpBW+LteLL71tILYPuyNeuYV69960ZwqH5QME+xvBdXA4Pqg5mFcWNiLEA3uUQzFEeWM/HDrk2hv10bI0gv1S7dKH13fehZPcCWYqIhzP75lMpzJ0Vpj3tGVW0ZBCSNDXEox+BSyboer89/YBEpGnXvb8eSvsg9wL0ElD1mEEPaJwSwV2Pu2SVVoa2Js/tzUeS1p/gkbHMDsewjs4S+V2a9J/5xG3xm+F3E/A7Zz2VogE/apYRDhUY/YyqHVFeMpEjbsO4qhBUVPQ6qEhB6CZN5rKn0KNjiTwIAjRm6S27sp9WDziWj2ec3ZESkIvpXnLKar1/2wJgBPNJeT5WlZiNwkrrn9KFFfXmDkBuTaWfqyzy6k/HJz3MHA2nb3/AUjd3XWtr1ieT5i7LTcgBXza+Xf4Ez5ZbxfBrrXvGVUsbOHy1luA0Uplbk1Uqq25Z78e5PDjOG0VaK1QN/OUAmHusgq5QqRIqDuALwZPyN4Iq9oW694PsrHNAbaBkqqovv+rfN53C3eqdsjXl95HOVKs+MkxXA+TOkh+LDmxh7fW7JZjDn1qMiTo24B5qhcEVSN4b1CrJsPVrB71R6tj93dIxtPzJrsBvHiVW4/gzCvL0XLyjwIh0tXkB4NwzMWmMW3RILY1Ho2qoyF2gX7wI=
  true:
    branch: master
    tags: true
install: pip install .
language: python
python: 2.7
script:
- black --check .
- python setup.py test
sudo: true
