language: python
python:
- '3.6.5'

sudo: required

install:
- pip install .

# Run the doctest
script:
- python setup.py test

deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: lATqIhtOVTlRw7hfHiXh02+2Rk+d9yQ6xcCFF5gezfCZ8tbCP7Opc+GR7ue61MHa63e9VEslolFltDkoOb0I/sS+NWISymZw2rooYkalRoIYYUJVZyRX8I+mgX8bzFAdBEfaf1cEBqdzUOvATIySsQX+s8CkLfpr/YKXFXXRfg/uSKR4Cb3hChrLChErLsl3KAlrxIoW59TS62jbyyrgKZerTni86dN0rG9DAr8xBwWO86cssfk8x2+S9BXUV6BBNs8uCZABD2Hb5342P6LptetLllN8NBO8T+SQIxKaSHj8ySyV2xm0U0XPkUHkVdg9iEMEi/8k60fw6l3ywgZGzHkxvVjgLbfDXsYCybHlgaabDoZZNejS4Uz7W9Y0jobU+vqWlIO6KcQ9rWYCaueDvMR0zaYUGn23XKrC6VjFuGXGPbVZhckssS9IP/Pljz4t/FxQgQ05Ob65mA2JfUWoM/I83tdFv3OMB0dGDQOMZNgOU0O+nuIZ2fZGRQoHuA8lMnlpeVHlrHwfjMiSC+BmKhODdg1EOTFjO8ThiusYvQW1Xc2DsxqFr7CDYtiJQphcw5nxXPA0sVS1VYhk/okrwDSb3Q7iUt+spsvYmbWGqzjEcEbY5Y+zycHHZQjeeIsiVhkJnXAPmZY0U9HAKrZbUR/rOM9SqOCs8v0D+bJxkYU=
  name: logagg-utils-0.5.0
  tag_name: 0.5.0
  on:
    branch: master
    repo: deep-compute/logagg-utils
